import { Case } from "../store/useStore";
import { generateRandomBirthDate } from "../utils/date";

const generateRandomId = () => {
  return Math.floor(100000 + Math.random() * 900000).toString();
};

export const sampleCases: Case[] = [
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Ready for Assignment",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Signed",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Scheduled",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Scheduled",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Scheduled",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Scheduled",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Scheduled",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: generateRandomId(),
    client_name: "Carlos Cox",
    date_of_birth: generateRandomBirthDate(),
    doa: "1/25/2025",
    medical_status: "Scheduled",
    case_status: "Active",
    law_firm: "XYZ Law",
    expenses: [],
  },
  {
    id: "221901",
    client_name: "Greg Conner",
    date_of_birth: "10/1/1961",
    doa: "10/1/1971",
    medical_status: "Ready for Assignment",
    case_status: "Pending",
    law_firm: "Julian Sanders & Associates",
    expenses: [
      {
        id: "1",
        label: "Lyft 05/12/2024",
        amount: 45.12,
        deductedFrom: "Client Settlement",
      },
      {
        id: "2",
        label: "Lyft 05/02/2024",
        amount: 38.23,
        deductedFrom: "Client Settlement",
      },
      {
        id: "3",
        label: "Lyft 04/23/2024",
        amount: 20.39,
        deductedFrom: "Client Settlement",
      },
    ],
  },
  {
    id: generateRandomId(),
    client_name: "Maria Smith",
    date_of_birth: generateRandomBirthDate(),
    doa: "3/15/2025",
    medical_status: "Completed",
    case_status: "Closed",
    law_firm: "ABC Legal",
    expenses: [],
  },
];
